### PR TITLE
update to latest python microsoft store url (3.13)

### PR DESCRIPTION
**Pull request by jnackmclain**

### CODE REVIEW

**Comment by DarkRTA** [comment]
i hate how this absolute troll of a PR just to snipe #400 is also legitimate

**Comment by DarkRTA** [comment]
also i've got bad news
image

**Comment by jnackmclain** [comment]
@DarkRTA fixed, my sincere apologies for the mistake. Thank you for taking the time to accurately review and approve my pull request. I hope you have a nice day.
Best wishes, jnack

**Review by DarkRTA — APPROVED** [review]
mfw

**Pull request merged**
