### PR TITLE
Pull in latest dtk-template changes; support progress categories

### PR DESCRIPTION
**Pull request by TheNathannator**
With some tidy along the way.

`flags.json` is now `config.json`, progress categories are stored there alongside the flag sets. Also improved the JSON schema a little to point out missing required keys.

### CODE REVIEW

**Comment by DarkRTA** [comment]
Couple of things before I merge this:
* Does this affect our progress upload in any way? I don't think things are set up on frogress for us to have multiple categories.
* We also need to standardize on categories between here and https://decomp.milohax.org/

**Comment by TheNathannator** [comment]
I'm not sure whether this affects progress uploads, would need to ask Encounter.

I didn't realize the site had its own categories already lol, I'll update the category names to match what that has already. I do think it would be worth giving the network folder its own category, it's a very significant amount of code. Otherwise that's the only addition I think we need, the `main` category I added can be merged into `band3`.

**Comment by DarkRTA** [comment]
i don't like the categories currently on the website and intend to redo them at some point

might as well get it out of the way now

**Comment by TheNathannator** [comment]
In that case, what in particular do you suggest? I don't have any strong opinions for that, outside of what should be separated into its own category (which can be further subdivided if desired).

**Comment by DarkRTA** [comment]
We can probably work things out when I get home in a few hours. Trying to discuss this while at work isn't the best idea lol.

**Comment by TheNathannator** [comment]
That's fair lol, I'll leave the categories as-is for now then.

**Comment by DarkRTA** [comment]
lgtm

**Pull request merged**
